name: story_create
description: A minimalist story creation app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State & UI
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^2.0.1
  photo_view: ^0.15.0

  # Files & Media
  image_picker: ^1.0.4
  file_picker: ^10.3.10
  path_provider: ^2.1.1
  path: ^1.9.0

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Audio / Video
  ffmpeg_kit_flutter_new: ^4.1.0
  video_player: ^2.8.3
  audioplayers: ^6.5.1
  record: ^6.1.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.2.0
  shimmer: ^3.0.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
